services:
  web:
    build: .
    command: gunicorn credit_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A credit_system beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env 